#!/bin/bash

#// Multimonitor Screen Setup for X
#// by Tony Bates 2013-11-26
#//
#// Requires xrandr, xmessage, grep , awk
#// Only Supports 2 Monitors


SCREENS=( $(xrandr | grep " connected" | awk '{print $1}') )
echo Screens Detected: ${SCREENS[@]}

if  [ "${#SCREENS[@]}" -gt "1" ]
 then
 #// More than 1 monitor found
 echo More than 1 monitor detected
 text="Monitors Detected: #1-${SCREENS[0]} #2-${SCREENS[1]}"
 xmessage -center -title "Monitor Setup" -buttons "Cancel":0,"Screen 1 Left":1,"Screen 1 Right":2,"Screen 1 Only":3,"Screen 2 Only":4,"Mirror Screen 1":5,"Mirror Screen 2":6 $text
 ans=$?
fi

if  [ "${#SCREENS[@]}" -lt "2" ]
 then
 #// Only one monitor found (less than 2 monitors)
 echo Only 1 monitor detected
 xmessage -center -title "Monitor Setup" "Only one Monitor found. No actions allowed."
fi

#// Screen 1 aka SCREENS[0], Screen 2 aka SCREENS[1]

if [ "$ans" == 1 ]
 then
  #// Screen 1 Left, Screen 2 Right
  xrandr --output ${SCREENS[0]} --auto --output ${SCREENS[1]} --auto --right-of ${SCREENS[0]}
fi

if [ "$ans" == 2 ]
 then
  #// Screen 2 Left, Screen 1 Right
  xrandr --output ${SCREENS[0]} --auto --output ${SCREENS[1]} --auto --left-of ${SCREENS[0]}
fi

if [ "$ans" == 3 ]
 then
  #// Screen 1 Only, Screen 2 Off
  xrandr --output ${SCREENS[1]} --off
  xrandr --output ${SCREENS[0]} --auto
fi

if [ "$ans" == 4 ]
 then
  #// Screen 2 Only, Screen 1 Off
  xrandr --output ${SCREENS[0]} --off
  xrandr --output ${SCREENS[1]} --auto
fi

if [ "$ans" == 5 ]
 then
  #// Mirror Screen 1 to Screen 2
  xrandr --output ${SCREENS[0]} --auto --output ${SCREENS[1]} --auto --same-as ${SCREENS[0]}
fi

if [ "$ans" == 6 ]
 then
  #// Mirror Screen 2 to Screen 1
  xrandr --output ${SCREENS[1]} --auto --same-as ${SCREENS[0]} --output ${SCREENS[0]} --auto
fi
